version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: yourStrongPassword123
    ports:
      - "5000:1433"
